version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysqldb
    volumes:
      - ./docker/db/housing_projects_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: CyjUavtTojBGiC(V
      MYSQL_USER: db_admin
      MYSQL_PASSWORD: CyjUavtTojBGiC(V
      MYSQL_DATABASE: housing_projects_db
    ports:
      - "3306:3306"
    networks:
      - cb-network
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - cb-network
  backend_cb:
    depends_on:
      - mysqldb
    container_name: oauth2-openid-project
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/housing_projects_db?useSSL=false",
              "spring.datasource.username" : "db_admin",
              "spring.datasource.password" : "CyjUavtTojBGiC(V",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    networks:
      - cb-network
networks:
  cb-network:
    driver: bridge

